//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeLab.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FakeLab.Resources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot cast value at [{0}, {1}] of type &apos;{2}&apos; to &apos;{3}&apos;..
        /// </summary>
        internal static string CastError {
            get {
                return ResourceManager.GetString("CastError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cyclic reference detected for type &apos;{0}&apos;..
        /// </summary>
        internal static string CyclicReferenceError {
            get {
                return ResourceManager.GetString("CyclicReferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The range is outside the valid boundaries of the numeric type..
        /// </summary>
        internal static string InfiniteError {
            get {
                return ResourceManager.GetString("InfiniteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect range of &apos;{0}&apos; and &apos;{1}&apos; values..
        /// </summary>
        internal static string InvalidDecimalRangeError {
            get {
                return ResourceManager.GetString("InvalidDecimalRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generated value type &apos;{0}&apos; is not assignable to property type &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidPropertyAssignment {
            get {
                return ResourceManager.GetString("InvalidPropertyAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Length cannot be less than or equal to zero..
        /// </summary>
        internal static string LengthArgumentError {
            get {
                return ResourceManager.GetString("LengthArgumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;{0}&apos; cannot be greater than &apos;{1}&apos;..
        /// </summary>
        internal static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Numerical value &apos;{0}&apos; is unknown..
        /// </summary>
        internal static string UnknownNumericalValue {
            get {
                return ResourceManager.GetString("UnknownNumericalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string UnsupportedTypeError {
            get {
                return ResourceManager.GetString("UnsupportedTypeError", resourceCulture);
            }
        }
    }
}
